---

- name: configs > Templates
  template:
    src:  "{{ item.template|default(manala_supervisor_configs_template|ternary(manala_supervisor_configs_template, 'configs/empty.j2')) }}"
    dest: "{{ manala_supervisor_configs_dir }}/{{ item.file }}"
  with_items: "{{ manala_supervisor_configs }}"
  notify:
    - supervisor restart

- name: configs > Exclusive - find files
  command: "find -type f -printf '%P\n'"
  args:
    chdir: "{{ manala_supervisor_configs_dir }}"
  changed_when: false
  register: __manala_supervisor_configs_find_output
  when: manala_supervisor_configs_exclusive

- name: configs > Clean
  file:
    path:  "{{ manala_supervisor_configs_dir }}/{{ item }}"
    state: absent
  when: manala_supervisor_configs_exclusive and (item not in manala_supervisor_configs|map(attribute='file'))
  with_items: "{{ __manala_supervisor_configs_find_output.stdout_lines|default([]) }}"
  notify:
    - supervisor restart
